USE WAREHOUSE GQH_WH;
USE DATABASE GQH_CRYPTO;
USE SCHEMA ML_DATA;

CREATE OR REPLACE VIEW
    GQH_CRYPTO.ML_DATA.MEAN_REVERSION_DATA_ADX_4H AS
SELECT
    f.*,
    p.HMM_STATE,
    p.REGIME,
    p.STATE_CONFIDENCE,
    p.RANGE_PROBABILITY,
    p.ADX_14
FROM GQH_CRYPTO.ML_DATA.REGIME_FEATURES_4H AS f
JOIN GQH_CRYPTO.ML_DATA.REGIME_PREDICTIONS_ADX_4H AS p
    ON f.ASSET = p.ASSET
   AND f.TIME = p.TIME
   AND f.BAR_END_TIME = p.BAR_END_TIME
   AND f.DATASET_ROLE = p.DATASET_ROLE;

CREATE OR REPLACE VIEW
    GQH_CRYPTO.ML_DATA.MEAN_REVERSION_SIGNALS_ADX_4H AS
WITH conditions AS (
    SELECT
        d.*,
        COALESCE(
            RETURN_1 < 0 AND DROP_ZSCORE <= -2,
            FALSE
        ) AS LARGE_DROP,
        COALESCE(
            FEAR_GREED_SCORE <= 25,
            FALSE
        ) AS NEGATIVE_SENTIMENT,
        COALESCE(
            REGIME = 'RANGE_CANDIDATE',
            FALSE
        ) AS RANGE_FILTER
    FROM GQH_CRYPTO.ML_DATA.MEAN_REVERSION_DATA_ADX_4H AS d
)
SELECT
    c.*,
    (
        COALESCE(FEATURES_READY, FALSE)
        AND LARGE_DROP
        AND NEGATIVE_SENTIMENT
        AND RANGE_FILTER
    ) AS ENTRY_SIGNAL
FROM conditions AS c;

SELECT
    ASSET,
    DATASET_ROLE,
    COUNT(*) AS EVALUATION_ROWS,
    COUNT_IF(LARGE_DROP) AS DROP_ONLY,
    COUNT_IF(
        LARGE_DROP AND NEGATIVE_SENTIMENT
    ) AS DROP_AND_FEAR,
    COUNT_IF(
        LARGE_DROP AND RANGE_FILTER
    ) AS DROP_AND_RANGE,
    COUNT_IF(ENTRY_SIGNAL) AS FULL_SIGNAL
FROM GQH_CRYPTO.ML_DATA.MEAN_REVERSION_SIGNALS_ADX_4H
WHERE FEATURES_READY
  AND TARGET_READY
GROUP BY ASSET, DATASET_ROLE
ORDER BY ASSET, DATASET_ROLE;