USE WAREHOUSE GQH_WH;
USE DATABASE GQH_CRYPTO;

CREATE SCHEMA IF NOT EXISTS ML_DATA;

USE SCHEMA ML_DATA;

SELECT
    ASSET,
    DATASET_ROLE,
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(FEATURES_READY) AS FEATURE_READY_ROWS,
    COUNT_IF(TARGET_READY) AS TARGET_READY_ROWS,
    COUNT_IF(
        FEATURES_READY AND TARGET_READY
    ) AS EVALUATION_READY_ROWS
FROM GQH_CRYPTO.ML_DATA.REGIME_FEATURES_4H
GROUP BY ASSET, DATASET_ROLE
ORDER BY ASSET, DATASET_ROLE;


SELECT
    ASSET,
    TIME,
    COUNT(*) AS ROW_COUNT
FROM GQH_CRYPTO.ML_DATA.REGIME_FEATURES_4H
GROUP BY ASSET, TIME
HAVING COUNT(*) > 1;

SELECT
    ASSET,
    DATASET_ROLE,
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(REGIME = 'RANGE_CANDIDATE') AS RANGE_ROWS
FROM GQH_CRYPTO.ML_DATA.REGIME_PREDICTIONS_4H
GROUP BY ASSET, DATASET_ROLE
ORDER BY ASSET, DATASET_ROLE;

SELECT
    ASSET,
    TIME,
    COUNT(*) AS ROW_COUNT
FROM GQH_CRYPTO.ML_DATA.REGIME_PREDICTIONS_4H
GROUP BY ASSET, TIME
HAVING COUNT(*) > 1;

CREATE OR REPLACE VIEW GQH_CRYPTO.ML_DATA.MEAN_REVERSION_DATA_4H AS
SELECT
    f.*,
    p.HMM_STATE,
    p.REGIME,
    p.STATE_CONFIDENCE,
    p.RANGE_PROBABILITY
FROM GQH_CRYPTO.ML_DATA.REGIME_FEATURES_4H AS f
JOIN GQH_CRYPTO.ML_DATA.REGIME_PREDICTIONS_4H AS p
    ON f.ASSET = p.ASSET
   AND f.TIME = p.TIME
   AND f.DATASET_ROLE = p.DATASET_ROLE
   AND f.BAR_END_TIME = p.BAR_END_TIME;

SELECT
    ASSET,
    DATASET_ROLE,
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(
        FEATURES_READY AND TARGET_READY
    ) AS EVALUATION_READY_ROWS
FROM GQH_CRYPTO.ML_DATA.MEAN_REVERSION_DATA_4H
GROUP BY ASSET, DATASET_ROLE
ORDER BY ASSET, DATASET_ROLE;

CREATE OR REPLACE VIEW GQH_CRYPTO.ML_DATA.MEAN_REVERSION_SIGNALS_4H AS
WITH conditions AS (
    SELECT
        d.*,

        COALESCE(
            RETURN_1 < 0 AND DROP_ZSCORE <= -2,
            FALSE
        ) AS LARGE_DROP,

        COALESCE(
            FEAR_GREED_SCORE <= 25,
            FALSE
        ) AS NEGATIVE_SENTIMENT,

        COALESCE(
            REGIME = 'RANGE_CANDIDATE',
            FALSE
        ) AS RANGE_FILTER

    FROM GQH_CRYPTO.ML_DATA.MEAN_REVERSION_DATA_4H AS d
)
SELECT
    c.*,

    (
        FEATURES_READY
        AND LARGE_DROP
        AND NEGATIVE_SENTIMENT
        AND RANGE_FILTER
    ) AS ENTRY_SIGNAL

FROM conditions AS c;


SELECT
    ASSET,
    DATASET_ROLE,
    COUNT(*) AS EVALUATION_ROWS,
    SUM(IFF(LARGE_DROP, 1, 0)) AS DROP_ONLY,

    SUM(IFF(
        LARGE_DROP AND NEGATIVE_SENTIMENT,
        1, 0
    )) AS DROP_AND_FEAR,

    SUM(IFF(
        LARGE_DROP AND RANGE_FILTER,
        1, 0
    )) AS DROP_AND_RANGE,

    SUM(IFF(ENTRY_SIGNAL, 1, 0)) AS FULL_SIGNAL

FROM GQH_CRYPTO.ML_DATA.MEAN_REVERSION_SIGNALS_4H
WHERE FEATURES_READY
  AND TARGET_READY
GROUP BY ASSET, DATASET_ROLE
ORDER BY ASSET, DATASET_ROLE;


WITH eligible AS (
    SELECT *
    FROM GQH_CRYPTO.ML_DATA.MEAN_REVERSION_SIGNALS_4H
    WHERE FEATURES_READY
      AND TARGET_READY
),
groups AS (
    SELECT
        ASSET, DATASET_ROLE, FORWARD_RETURN_1,
        '1_DROP_ONLY' AS SIGNAL_GROUP
    FROM eligible
    WHERE LARGE_DROP

    UNION ALL

    SELECT
        ASSET, DATASET_ROLE, FORWARD_RETURN_1,
        '2_DROP_AND_FEAR'
    FROM eligible
    WHERE LARGE_DROP AND NEGATIVE_SENTIMENT

    UNION ALL

    SELECT
        ASSET, DATASET_ROLE, FORWARD_RETURN_1,
        '3_DROP_AND_RANGE'
    FROM eligible
    WHERE LARGE_DROP AND RANGE_FILTER

    UNION ALL

    SELECT
        ASSET, DATASET_ROLE, FORWARD_RETURN_1,
        '4_FULL_SIGNAL'
    FROM eligible
    WHERE ENTRY_SIGNAL
)
SELECT
    ASSET,
    DATASET_ROLE,
    SIGNAL_GROUP,
    COUNT(*) AS OBSERVATIONS,
    ROUND(100 * AVG(FORWARD_RETURN_1), 4)
        AS AVG_REBOUND_PCT,
    ROUND(100 * MEDIAN(FORWARD_RETURN_1), 4)
        AS MEDIAN_REBOUND_PCT,
    ROUND(
        100 * AVG(IFF(FORWARD_RETURN_1 > 0, 1.0, 0.0)),
        2
    ) AS POSITIVE_RETURN_PCT
FROM groups
GROUP BY ASSET, DATASET_ROLE, SIGNAL_GROUP
ORDER BY ASSET, DATASET_ROLE, SIGNAL_GROUP;


WITH checked AS (
    SELECT
        ASSET,
        TIME,
        BAR_END_TIME,
        CLOSE,
        DATASET_ROLE,
        DROP_ZSCORE,
        FEAR_GREED_SCORE,
        REGIME,
        ENTRY_SIGNAL,
        FEATURES_READY,
        TARGET_READY,
        FORWARD_RETURN_1,

        LEAD(TIME) OVER (
            PARTITION BY ASSET ORDER BY TIME
        ) AS NEXT_TIME,

        LEAD(CLOSE) OVER (
            PARTITION BY ASSET ORDER BY TIME
        ) AS NEXT_CLOSE

    FROM GQH_CRYPTO.ML_DATA.MEAN_REVERSION_SIGNALS_4H
)
SELECT
    ASSET,
    BAR_END_TIME AS SIGNAL_TIME,
    CLOSE,
    NEXT_CLOSE,
    DATEDIFF('second', TIME, NEXT_TIME) / 3600.0
        AS HOURS_TO_NEXT_BAR,
    DROP_ZSCORE,
    FEAR_GREED_SCORE,
    ROUND(100 * FORWARD_RETURN_1, 4)
        AS STORED_RETURN_PCT,
    ROUND(100 * (NEXT_CLOSE / CLOSE - 1), 4)
        AS RECOMPUTED_RETURN_PCT
FROM checked
WHERE DATASET_ROLE = 'REGIME_VALIDATION'
  AND FEATURES_READY
  AND TARGET_READY
  AND ENTRY_SIGNAL
ORDER BY ASSET, SIGNAL_TIME;

SELECT
    f.ASSET,
    f.DATASET_ROLE,
    COUNT(*) AS FEATURE_READY_ROWS,
    COUNT_IF(p.TIME IS NULL) AS MISSING_PREDICTIONS
FROM GQH_CRYPTO.ML_DATA.REGIME_FEATURES_4H AS f
LEFT JOIN GQH_CRYPTO.ML_DATA.REGIME_PREDICTIONS_4H AS p
    ON f.ASSET = p.ASSET
   AND f.TIME = p.TIME
   AND f.DATASET_ROLE = p.DATASET_ROLE
   AND f.BAR_END_TIME = p.BAR_END_TIME
WHERE f.FEATURES_READY
GROUP BY f.ASSET, f.DATASET_ROLE
ORDER BY f.ASSET, f.DATASET_ROLE;

WITH eligible AS (
    SELECT *
    FROM GQH_CRYPTO.ML_DATA.MEAN_REVERSION_SIGNALS_4H
    WHERE DATASET_ROLE = 'REGIME_VALIDATION'
      AND FEATURES_READY
      AND TARGET_READY
),
signal_groups AS (
    SELECT ASSET, FORWARD_RETURN_1,
           '1_DROP_ONLY' AS VARIANT
    FROM eligible
    WHERE LARGE_DROP

    UNION ALL

    SELECT ASSET, FORWARD_RETURN_1,
           '2_DROP_AND_FEAR'
    FROM eligible
    WHERE LARGE_DROP AND NEGATIVE_SENTIMENT

    UNION ALL

    SELECT ASSET, FORWARD_RETURN_1,
           '3_DROP_AND_RANGE'
    FROM eligible
    WHERE LARGE_DROP AND RANGE_FILTER

    UNION ALL

    SELECT ASSET, FORWARD_RETURN_1,
           '4_FULL_SIGNAL'
    FROM eligible
    WHERE ENTRY_SIGNAL
)
SELECT
    ASSET,
    VARIANT,
    COUNT(*) AS SIGNAL_COUNT,
    ROUND(100 * AVG(FORWARD_RETURN_1), 4)
        AS AVG_RETURN_PCT,
    ROUND(100 * MEDIAN(FORWARD_RETURN_1), 4)
        AS MEDIAN_RETURN_PCT,
    ROUND(
        100 * AVG(IFF(FORWARD_RETURN_1 > 0, 1.0, 0.0)),
        2
    ) AS POSITIVE_RETURN_PCT
FROM signal_groups
GROUP BY ASSET, VARIANT
ORDER BY ASSET, VARIANT;

