USE WAREHOUSE GQH_WH;
USE DATABASE GQH_CRYPTO;
USE SCHEMA ML_DATA;

CREATE OR REPLACE VIEW REGIME_FEATURES_ADX_4H AS
SELECT
    f.*,
    a.PLUS_DI_14,
    a.MINUS_DI_14,
    a.ADX_14
FROM GQH_CRYPTO.ML_DATA.REGIME_FEATURES_4H AS f
LEFT JOIN GQH_CRYPTO.ML_DATA.MARKET_ADX_4H AS a
    ON f.ASSET = a.ASSET
   AND f.TIME = a.TIME
   AND f.BAR_END_TIME = a.BAR_END_TIME
   AND a.DATASET = 'GLBX.MDP3';

SELECT
    ASSET,
    DATASET_ROLE,
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(FEATURES_READY AND ADX_14 IS NOT NULL)
        AS MODEL_READY_ROWS
FROM REGIME_FEATURES_ADX_4H
GROUP BY ASSET, DATASET_ROLE
ORDER BY ASSET, DATASET_ROLE;