USE DATABASE GQH_CRYPTO;

CREATE SCHEMA IF NOT EXISTS ML_DATA;

CREATE TABLE IF NOT EXISTS GQH_CRYPTO.ML_DATA.REGIME_FEATURES_4H (
    TIME TIMESTAMP_TZ(9),
    ASSET VARCHAR(16777216),
    BAR_END_TIME TIMESTAMP_TZ(9),
    CLOSE FLOAT,
    VOLUME FLOAT,
    SENTIMENT_ASSUMED_AVAILABLE_AT TIMESTAMP_TZ(9),
    RETURN_1 FLOAT,
    RETURN_6 FLOAT,
    RETURN_30 FLOAT,
    DROP_ZSCORE FLOAT,
    VOLATILITY_30 FLOAT,
    SMA_DISTANCE_20 FLOAT,
    SMA_20_50_SPREAD FLOAT,
    BB_WIDTH FLOAT,
    BB_POSITION FLOAT,
    VOLUME_ZSCORE FLOAT,
    FEAR_GREED_SCORE FLOAT,
    FORWARD_RETURN_1 FLOAT,
    DATASET_ROLE VARCHAR(16777216),
    FEATURES_READY BOOLEAN,
    TARGET_READY BOOLEAN
);

CREATE TABLE IF NOT EXISTS GQH_CRYPTO.ML_DATA.REGIME_PREDICTIONS_4H (
    TIME TIMESTAMP_TZ(9),
    BAR_END_TIME TIMESTAMP_TZ(9),
    ASSET VARCHAR(16777216),
    DATASET_ROLE VARCHAR(16777216),
    HMM_STATE NUMBER(38,0),
    REGIME VARCHAR(16777216),
    STATE_CONFIDENCE FLOAT,
    RANGE_PROBABILITY FLOAT
);